### ISSUE TITLE
Update guetzli

### ISSUE THREAD

**Issue by Razunter** [imagemin/guetzli-bin#2]
Please update guetzli to a new version. Current one crashes often.
imagemin-guetzli will require minor adjustment too (--quality vs -quality)

**Comment by qiaoyan** [comment]
currently (2017-04-13) master build error?

**Comment by bradbaris** [comment]
Bumped guetzli up to `v1.0.1` and updated `imagemin-guetzli` as well.

The build error you might be seeing is likely addressed in #5
